[DATA]
dataset = "https://raw.githubusercontent.com/5x12/ml-cookbook/master/supplements/data/heart.csv"
[MODEL]
dt_conf = "models/conf/decision_tree.pkl"
[PREDICTION]
parameters = [[59, 1, 0, 101, 234, 0, 1, 143, 0, 3.4, 0, 0, 0]]